import { computed, shallowRef } from 'vue'

const jsonEditorThemePresets = {
  light: {
    hint: '默认浅色主题',
    label: '浅色',
    preview: {
      background: '#fbfcfb',
      color: '#17211f',
    },
    requiresDarkBase: false,
    variables: {
      '--jse-background-color': '#fbfcfb',
      '--jse-context-menu-background': '#ffffff',
      '--jse-context-menu-color': '#17211f',
      '--jse-hover-background-color': '#edf6f3',
      '--jse-menu-color': '#f7fbfa',
      '--jse-navigation-bar-background': '#edf2f0',
      '--jse-navigation-bar-background-highlight': '#e2ebe7',
      '--jse-panel-background': '#f3f6f5',
      '--jse-panel-background-border': '1px solid #d8e0dd',
      '--jse-selection-background-color': '#d8eee8',
      '--jse-theme-color': '#0f766e',
      '--jse-theme-color-highlight': '#168a81',
    },
  },
  dark: {
    hint: 'vanilla-jsoneditor 深色主题',
    label: '深色',
    preview: {
      background: '#111817',
      color: '#dce9e5',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-context-menu-background': '#ffffff',
      '--jse-context-menu-color': '#17211f',
      '--jse-menu-color': '#eef6f3',
      '--jse-theme-color': '#314f49',
      '--jse-theme-color-highlight': '#41685f',
    },
  },
  dracula: {
    hint: '基于 Dracula VS Code 主题配色',
    label: 'Dracula',
    preview: {
      background: '#282a36',
      color: '#f8f8f2',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(255, 255, 255, 0.06)',
      '--jse-background-color': '#282a36',
      '--jse-button-background': '#6272a4',
      '--jse-button-background-highlight': '#7082b6',
      '--jse-button-color': '#f8f8f2',
      '--jse-collapsed-items-background-color': '#343746',
      '--jse-context-menu-background': '#f8f8f2',
      '--jse-context-menu-background-highlight': '#e8e8e2',
      '--jse-context-menu-color': '#282a36',
      '--jse-delimiter-color': '#6272a4',
      '--jse-hover-background-color': 'rgba(189, 147, 249, 0.16)',
      '--jse-input-background': '#21222c',
      '--jse-key-color': '#8be9fd',
      '--jse-main-border': '1px solid #44475a',
      '--jse-menu-color': '#f8f8f2',
      '--jse-modal-background': '#282a36',
      '--jse-modal-code-background': '#21222c',
      '--jse-navigation-bar-background': '#343746',
      '--jse-navigation-bar-background-highlight': '#44475a',
      '--jse-panel-background': '#21222c',
      '--jse-panel-background-border': '1px solid #44475a',
      '--jse-panel-button-background-highlight': '#44475a',
      '--jse-panel-color': '#f8f8f2',
      '--jse-selection-background-color': '#44475a',
      '--jse-table-header-background': '#21222c',
      '--jse-table-header-background-highlight': '#44475a',
      '--jse-text-color': '#f8f8f2',
      '--jse-text-color-inverse': '#282a36',
      '--jse-theme-color': '#bd93f9',
      '--jse-theme-color-highlight': '#ff79c6',
      '--jse-tooltip-background': '#44475a',
      '--jse-tooltip-border': '1px solid #6272a4',
      '--jse-value-color': '#f8f8f2',
      '--jse-value-color-boolean': '#ff79c6',
      '--jse-value-color-null': '#ff79c6',
      '--jse-value-color-number': '#bd93f9',
      '--jse-value-color-string': '#f1fa8c',
      '--jse-value-color-url': '#50fa7b',
    },
  },
  nord: {
    hint: '基于 Nord VS Code 主题配色',
    label: 'Nord',
    preview: {
      background: '#2e3440',
      color: '#e5e9f0',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(236, 239, 244, 0.06)',
      '--jse-background-color': '#2e3440',
      '--jse-button-background': '#5e81ac',
      '--jse-button-background-highlight': '#81a1c1',
      '--jse-button-color': '#eceff4',
      '--jse-collapsed-items-background-color': '#3b4252',
      '--jse-context-menu-background': '#eceff4',
      '--jse-context-menu-background-highlight': '#d8dee9',
      '--jse-context-menu-color': '#2e3440',
      '--jse-delimiter-color': '#d8dee9',
      '--jse-hover-background-color': 'rgba(136, 192, 208, 0.16)',
      '--jse-input-background': '#242933',
      '--jse-key-color': '#81a1c1',
      '--jse-main-border': '1px solid #4c566a',
      '--jse-menu-color': '#eceff4',
      '--jse-modal-background': '#2e3440',
      '--jse-modal-code-background': '#242933',
      '--jse-navigation-bar-background': '#3b4252',
      '--jse-navigation-bar-background-highlight': '#4c566a',
      '--jse-panel-background': '#242933',
      '--jse-panel-background-border': '1px solid #3b4252',
      '--jse-panel-button-background-highlight': '#3b4252',
      '--jse-panel-color': '#e5e9f0',
      '--jse-selection-background-color': '#434c5e',
      '--jse-table-header-background': '#242933',
      '--jse-table-header-background-highlight': '#3b4252',
      '--jse-text-color': '#e5e9f0',
      '--jse-text-color-inverse': '#2e3440',
      '--jse-theme-color': '#88c0d0',
      '--jse-theme-color-highlight': '#8fbcbb',
      '--jse-tooltip-background': '#3b4252',
      '--jse-tooltip-border': '1px solid #4c566a',
      '--jse-value-color': '#e5e9f0',
      '--jse-value-color-boolean': '#88c0d0',
      '--jse-value-color-null': '#88c0d0',
      '--jse-value-color-number': '#b48ead',
      '--jse-value-color-string': '#a3be8c',
      '--jse-value-color-url': '#8fbcbb',
    },
  },
  catppuccin: {
    hint: '基于 Catppuccin Mocha VS Code 主题配色',
    label: 'Catppuccin',
    preview: {
      background: '#1e1e2e',
      color: '#cdd6f4',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(205, 214, 244, 0.06)',
      '--jse-background-color': '#1e1e2e',
      '--jse-button-background': '#585b70',
      '--jse-button-background-highlight': '#6c7086',
      '--jse-button-color': '#cdd6f4',
      '--jse-collapsed-items-background-color': '#313244',
      '--jse-context-menu-background': '#f5e0dc',
      '--jse-context-menu-background-highlight': '#f2cdcd',
      '--jse-context-menu-color': '#1e1e2e',
      '--jse-delimiter-color': '#bac2de',
      '--jse-hover-background-color': 'rgba(137, 180, 250, 0.16)',
      '--jse-input-background': '#181825',
      '--jse-key-color': '#89b4fa',
      '--jse-main-border': '1px solid #45475a',
      '--jse-menu-color': '#cdd6f4',
      '--jse-modal-background': '#1e1e2e',
      '--jse-modal-code-background': '#181825',
      '--jse-navigation-bar-background': '#313244',
      '--jse-navigation-bar-background-highlight': '#45475a',
      '--jse-panel-background': '#181825',
      '--jse-panel-background-border': '1px solid #313244',
      '--jse-panel-button-background-highlight': '#313244',
      '--jse-panel-color': '#cdd6f4',
      '--jse-selection-background-color': '#313244',
      '--jse-table-header-background': '#181825',
      '--jse-table-header-background-highlight': '#313244',
      '--jse-text-color': '#cdd6f4',
      '--jse-text-color-inverse': '#1e1e2e',
      '--jse-theme-color': '#89b4fa',
      '--jse-theme-color-highlight': '#cba6f7',
      '--jse-tooltip-background': '#313244',
      '--jse-tooltip-border': '1px solid #585b70',
      '--jse-value-color': '#cdd6f4',
      '--jse-value-color-boolean': '#f38ba8',
      '--jse-value-color-null': '#f38ba8',
      '--jse-value-color-number': '#fab387',
      '--jse-value-color-string': '#a6e3a1',
      '--jse-value-color-url': '#94e2d5',
    },
  },
  oneDarkPro: {
    hint: '参考 VS Code 热门主题 One Dark Pro',
    label: 'One Dark Pro',
    preview: {
      background: '#282c34',
      color: '#abb2bf',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(171, 178, 191, 0.08)',
      '--jse-background-color': '#282c34',
      '--jse-button-background': '#3e4451',
      '--jse-button-background-highlight': '#4b5263',
      '--jse-button-color': '#abb2bf',
      '--jse-collapsed-items-background-color': '#2c313c',
      '--jse-context-menu-background': '#f0f3f7',
      '--jse-context-menu-background-highlight': '#dfe5ee',
      '--jse-context-menu-color': '#282c34',
      '--jse-delimiter-color': '#5c6370',
      '--jse-hover-background-color': 'rgba(97, 175, 239, 0.14)',
      '--jse-input-background': '#21252b',
      '--jse-key-color': '#e06c75',
      '--jse-main-border': '1px solid #3e4451',
      '--jse-menu-color': '#abb2bf',
      '--jse-modal-background': '#282c34',
      '--jse-modal-code-background': '#21252b',
      '--jse-navigation-bar-background': '#2f343f',
      '--jse-navigation-bar-background-highlight': '#3e4451',
      '--jse-panel-background': '#21252b',
      '--jse-panel-background-border': '1px solid #3e4451',
      '--jse-panel-button-background-highlight': '#3e4451',
      '--jse-panel-color': '#abb2bf',
      '--jse-selection-background-color': '#3e4451',
      '--jse-table-header-background': '#21252b',
      '--jse-table-header-background-highlight': '#3e4451',
      '--jse-text-color': '#abb2bf',
      '--jse-text-color-inverse': '#282c34',
      '--jse-theme-color': '#61afef',
      '--jse-theme-color-highlight': '#528bff',
      '--jse-tooltip-background': '#3e4451',
      '--jse-tooltip-border': '1px solid #5c6370',
      '--jse-value-color': '#abb2bf',
      '--jse-value-color-boolean': '#c678dd',
      '--jse-value-color-null': '#c678dd',
      '--jse-value-color-number': '#d19a66',
      '--jse-value-color-string': '#98c379',
      '--jse-value-color-url': '#56b6c2',
    },
  },
  monokaiPro: {
    hint: '参考 VS Code 热门主题 Monokai Pro',
    label: 'Monokai Pro',
    preview: {
      background: '#2d2a2e',
      color: '#fcfcfa',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(255, 255, 255, 0.06)',
      '--jse-background-color': '#2d2a2e',
      '--jse-button-background': '#5b595c',
      '--jse-button-background-highlight': '#727072',
      '--jse-button-color': '#fcfcfa',
      '--jse-collapsed-items-background-color': '#403e41',
      '--jse-context-menu-background': '#fcfcfa',
      '--jse-context-menu-background-highlight': '#ececea',
      '--jse-context-menu-color': '#2d2a2e',
      '--jse-delimiter-color': '#939293',
      '--jse-hover-background-color': 'rgba(255, 97, 136, 0.14)',
      '--jse-input-background': '#221f22',
      '--jse-key-color': '#ff6188',
      '--jse-main-border': '1px solid #5b595c',
      '--jse-menu-color': '#fcfcfa',
      '--jse-modal-background': '#2d2a2e',
      '--jse-modal-code-background': '#221f22',
      '--jse-navigation-bar-background': '#403e41',
      '--jse-navigation-bar-background-highlight': '#5b595c',
      '--jse-panel-background': '#221f22',
      '--jse-panel-background-border': '1px solid #5b595c',
      '--jse-panel-button-background-highlight': '#5b595c',
      '--jse-panel-color': '#fcfcfa',
      '--jse-selection-background-color': '#5b595c',
      '--jse-table-header-background': '#221f22',
      '--jse-table-header-background-highlight': '#403e41',
      '--jse-text-color': '#fcfcfa',
      '--jse-text-color-inverse': '#2d2a2e',
      '--jse-theme-color': '#ffd866',
      '--jse-theme-color-highlight': '#ff6188',
      '--jse-tooltip-background': '#403e41',
      '--jse-tooltip-border': '1px solid #727072',
      '--jse-value-color': '#fcfcfa',
      '--jse-value-color-boolean': '#ab9df2',
      '--jse-value-color-null': '#ab9df2',
      '--jse-value-color-number': '#ab9df2',
      '--jse-value-color-string': '#a9dc76',
      '--jse-value-color-url': '#78dce8',
    },
  },
  githubDark: {
    hint: '参考 VS Code 热门主题 GitHub Dark',
    label: 'GitHub Dark',
    preview: {
      background: '#0d1117',
      color: '#c9d1d9',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(201, 209, 217, 0.06)',
      '--jse-background-color': '#0d1117',
      '--jse-button-background': '#238636',
      '--jse-button-background-highlight': '#2ea043',
      '--jse-button-color': '#ffffff',
      '--jse-collapsed-items-background-color': '#161b22',
      '--jse-context-menu-background': '#f0f6fc',
      '--jse-context-menu-background-highlight': '#dbe7f3',
      '--jse-context-menu-color': '#0d1117',
      '--jse-delimiter-color': '#8b949e',
      '--jse-hover-background-color': 'rgba(88, 166, 255, 0.14)',
      '--jse-input-background': '#010409',
      '--jse-key-color': '#79c0ff',
      '--jse-main-border': '1px solid #30363d',
      '--jse-menu-color': '#f0f6fc',
      '--jse-modal-background': '#0d1117',
      '--jse-modal-code-background': '#010409',
      '--jse-navigation-bar-background': '#161b22',
      '--jse-navigation-bar-background-highlight': '#21262d',
      '--jse-panel-background': '#010409',
      '--jse-panel-background-border': '1px solid #30363d',
      '--jse-panel-button-background-highlight': '#21262d',
      '--jse-panel-color': '#c9d1d9',
      '--jse-selection-background-color': '#1f6feb55',
      '--jse-table-header-background': '#010409',
      '--jse-table-header-background-highlight': '#161b22',
      '--jse-text-color': '#c9d1d9',
      '--jse-text-color-inverse': '#0d1117',
      '--jse-theme-color': '#58a6ff',
      '--jse-theme-color-highlight': '#79c0ff',
      '--jse-tooltip-background': '#161b22',
      '--jse-tooltip-border': '1px solid #30363d',
      '--jse-value-color': '#c9d1d9',
      '--jse-value-color-boolean': '#ff7b72',
      '--jse-value-color-null': '#ff7b72',
      '--jse-value-color-number': '#a5d6ff',
      '--jse-value-color-string': '#a5d6ff',
      '--jse-value-color-url': '#7ee787',
    },
  },
  githubLight: {
    hint: '参考 VS Code 热门主题 GitHub Light',
    label: 'GitHub Light',
    preview: {
      background: '#ffffff',
      color: '#24292f',
    },
    requiresDarkBase: false,
    variables: {
      '--jse-background-color': '#ffffff',
      '--jse-context-menu-background': '#ffffff',
      '--jse-context-menu-background-highlight': '#f6f8fa',
      '--jse-context-menu-color': '#24292f',
      '--jse-delimiter-color': '#57606a',
      '--jse-hover-background-color': '#f6f8fa',
      '--jse-key-color': '#0550ae',
      '--jse-main-border': '1px solid #d0d7de',
      '--jse-menu-color': '#ffffff',
      '--jse-navigation-bar-background': '#f6f8fa',
      '--jse-navigation-bar-background-highlight': '#eaeef2',
      '--jse-panel-background': '#f6f8fa',
      '--jse-panel-background-border': '1px solid #d0d7de',
      '--jse-panel-color': '#24292f',
      '--jse-selection-background-color': '#ddf4ff',
      '--jse-table-header-background': '#f6f8fa',
      '--jse-table-header-background-highlight': '#eaeef2',
      '--jse-text-color': '#24292f',
      '--jse-theme-color': '#0969da',
      '--jse-theme-color-highlight': '#0550ae',
      '--jse-value-color-boolean': '#cf222e',
      '--jse-value-color-null': '#cf222e',
      '--jse-value-color-number': '#0550ae',
      '--jse-value-color-string': '#0a3069',
      '--jse-value-color-url': '#116329',
    },
  },
  materialPalenight: {
    hint: '参考 VS Code 热门主题 Material Palenight',
    label: 'Material Palenight',
    preview: {
      background: '#292d3e',
      color: '#a6accd',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(166, 172, 205, 0.08)',
      '--jse-background-color': '#292d3e',
      '--jse-button-background': '#676e95',
      '--jse-button-background-highlight': '#8796b0',
      '--jse-button-color': '#ffffff',
      '--jse-collapsed-items-background-color': '#32374d',
      '--jse-context-menu-background': '#ffffff',
      '--jse-context-menu-background-highlight': '#eef1ff',
      '--jse-context-menu-color': '#292d3e',
      '--jse-delimiter-color': '#676e95',
      '--jse-hover-background-color': 'rgba(130, 170, 255, 0.14)',
      '--jse-input-background': '#202331',
      '--jse-key-color': '#82aaff',
      '--jse-main-border': '1px solid #444267',
      '--jse-menu-color': '#a6accd',
      '--jse-modal-background': '#292d3e',
      '--jse-modal-code-background': '#202331',
      '--jse-navigation-bar-background': '#32374d',
      '--jse-navigation-bar-background-highlight': '#444267',
      '--jse-panel-background': '#202331',
      '--jse-panel-background-border': '1px solid #444267',
      '--jse-panel-button-background-highlight': '#444267',
      '--jse-panel-color': '#a6accd',
      '--jse-selection-background-color': '#444267',
      '--jse-table-header-background': '#202331',
      '--jse-table-header-background-highlight': '#32374d',
      '--jse-text-color': '#a6accd',
      '--jse-text-color-inverse': '#292d3e',
      '--jse-theme-color': '#c792ea',
      '--jse-theme-color-highlight': '#82aaff',
      '--jse-tooltip-background': '#32374d',
      '--jse-tooltip-border': '1px solid #676e95',
      '--jse-value-color': '#a6accd',
      '--jse-value-color-boolean': '#ff5370',
      '--jse-value-color-null': '#ff5370',
      '--jse-value-color-number': '#f78c6c',
      '--jse-value-color-string': '#c3e88d',
      '--jse-value-color-url': '#89ddff',
    },
  },
  ayuDark: {
    hint: '参考 VS Code 热门主题 Ayu Dark',
    label: 'Ayu Dark',
    preview: {
      background: '#0b0e14',
      color: '#b3b1ad',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(255, 255, 255, 0.05)',
      '--jse-background-color': '#0b0e14',
      '--jse-button-background': '#39bae6',
      '--jse-button-background-highlight': '#59c2ff',
      '--jse-button-color': '#0b0e14',
      '--jse-collapsed-items-background-color': '#11151c',
      '--jse-context-menu-background': '#f8f9fa',
      '--jse-context-menu-background-highlight': '#ebeef2',
      '--jse-context-menu-color': '#0b0e14',
      '--jse-delimiter-color': '#565b66',
      '--jse-hover-background-color': 'rgba(57, 186, 230, 0.14)',
      '--jse-input-background': '#06080d',
      '--jse-key-color': '#39bae6',
      '--jse-main-border': '1px solid #1f2430',
      '--jse-menu-color': '#b3b1ad',
      '--jse-modal-background': '#0b0e14',
      '--jse-modal-code-background': '#06080d',
      '--jse-navigation-bar-background': '#11151c',
      '--jse-navigation-bar-background-highlight': '#1f2430',
      '--jse-panel-background': '#06080d',
      '--jse-panel-background-border': '1px solid #1f2430',
      '--jse-panel-button-background-highlight': '#1f2430',
      '--jse-panel-color': '#b3b1ad',
      '--jse-selection-background-color': '#253340',
      '--jse-table-header-background': '#06080d',
      '--jse-table-header-background-highlight': '#11151c',
      '--jse-text-color': '#b3b1ad',
      '--jse-text-color-inverse': '#0b0e14',
      '--jse-theme-color': '#ffb454',
      '--jse-theme-color-highlight': '#ff8f40',
      '--jse-tooltip-background': '#11151c',
      '--jse-tooltip-border': '1px solid #1f2430',
      '--jse-value-color': '#b3b1ad',
      '--jse-value-color-boolean': '#ff8f40',
      '--jse-value-color-null': '#ff8f40',
      '--jse-value-color-number': '#ffb454',
      '--jse-value-color-string': '#aad94c',
      '--jse-value-color-url': '#95e6cb',
    },
  },
  nightOwl: {
    hint: '参考 VS Code 热门主题 Night Owl',
    label: 'Night Owl',
    preview: {
      background: '#011627',
      color: '#d6deeb',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(214, 222, 235, 0.06)',
      '--jse-background-color': '#011627',
      '--jse-button-background': '#7fdbca',
      '--jse-button-background-highlight': '#82aaff',
      '--jse-button-color': '#011627',
      '--jse-collapsed-items-background-color': '#0b2942',
      '--jse-context-menu-background': '#d6deeb',
      '--jse-context-menu-background-highlight': '#c4d1e4',
      '--jse-context-menu-color': '#011627',
      '--jse-delimiter-color': '#5f7e97',
      '--jse-hover-background-color': 'rgba(130, 170, 255, 0.14)',
      '--jse-input-background': '#00111f',
      '--jse-key-color': '#82aaff',
      '--jse-main-border': '1px solid #1d3b53',
      '--jse-menu-color': '#d6deeb',
      '--jse-modal-background': '#011627',
      '--jse-modal-code-background': '#00111f',
      '--jse-navigation-bar-background': '#0b2942',
      '--jse-navigation-bar-background-highlight': '#1d3b53',
      '--jse-panel-background': '#00111f',
      '--jse-panel-background-border': '1px solid #1d3b53',
      '--jse-panel-button-background-highlight': '#1d3b53',
      '--jse-panel-color': '#d6deeb',
      '--jse-selection-background-color': '#1d3b53',
      '--jse-table-header-background': '#00111f',
      '--jse-table-header-background-highlight': '#0b2942',
      '--jse-text-color': '#d6deeb',
      '--jse-text-color-inverse': '#011627',
      '--jse-theme-color': '#7fdbca',
      '--jse-theme-color-highlight': '#82aaff',
      '--jse-tooltip-background': '#0b2942',
      '--jse-tooltip-border': '1px solid #1d3b53',
      '--jse-value-color': '#d6deeb',
      '--jse-value-color-boolean': '#ff5874',
      '--jse-value-color-null': '#ff5874',
      '--jse-value-color-number': '#f78c6c',
      '--jse-value-color-string': '#ecc48d',
      '--jse-value-color-url': '#7fdbca',
    },
  },
  tokyoNight: {
    hint: '参考 VS Code 热门主题 Tokyo Night',
    label: 'Tokyo Night',
    preview: {
      background: '#1a1b26',
      color: '#c0caf5',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(192, 202, 245, 0.06)',
      '--jse-background-color': '#1a1b26',
      '--jse-button-background': '#7aa2f7',
      '--jse-button-background-highlight': '#bb9af7',
      '--jse-button-color': '#1a1b26',
      '--jse-collapsed-items-background-color': '#24283b',
      '--jse-context-menu-background': '#c0caf5',
      '--jse-context-menu-background-highlight': '#a9b1d6',
      '--jse-context-menu-color': '#1a1b26',
      '--jse-delimiter-color': '#565f89',
      '--jse-hover-background-color': 'rgba(122, 162, 247, 0.14)',
      '--jse-input-background': '#16161e',
      '--jse-key-color': '#7aa2f7',
      '--jse-main-border': '1px solid #414868',
      '--jse-menu-color': '#c0caf5',
      '--jse-modal-background': '#1a1b26',
      '--jse-modal-code-background': '#16161e',
      '--jse-navigation-bar-background': '#24283b',
      '--jse-navigation-bar-background-highlight': '#414868',
      '--jse-panel-background': '#16161e',
      '--jse-panel-background-border': '1px solid #414868',
      '--jse-panel-button-background-highlight': '#414868',
      '--jse-panel-color': '#c0caf5',
      '--jse-selection-background-color': '#33467c',
      '--jse-table-header-background': '#16161e',
      '--jse-table-header-background-highlight': '#24283b',
      '--jse-text-color': '#c0caf5',
      '--jse-text-color-inverse': '#1a1b26',
      '--jse-theme-color': '#bb9af7',
      '--jse-theme-color-highlight': '#7aa2f7',
      '--jse-tooltip-background': '#24283b',
      '--jse-tooltip-border': '1px solid #414868',
      '--jse-value-color': '#c0caf5',
      '--jse-value-color-boolean': '#ff9e64',
      '--jse-value-color-null': '#ff9e64',
      '--jse-value-color-number': '#ff9e64',
      '--jse-value-color-string': '#9ece6a',
      '--jse-value-color-url': '#7dcfff',
    },
  },
  gruvboxDark: {
    hint: '参考 VS Code 热门主题 Gruvbox Dark',
    label: 'Gruvbox Dark',
    preview: {
      background: '#282828',
      color: '#ebdbb2',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(235, 219, 178, 0.06)',
      '--jse-background-color': '#282828',
      '--jse-button-background': '#689d6a',
      '--jse-button-background-highlight': '#8ec07c',
      '--jse-button-color': '#282828',
      '--jse-collapsed-items-background-color': '#3c3836',
      '--jse-context-menu-background': '#fbf1c7',
      '--jse-context-menu-background-highlight': '#ebdbb2',
      '--jse-context-menu-color': '#282828',
      '--jse-delimiter-color': '#a89984',
      '--jse-hover-background-color': 'rgba(250, 189, 47, 0.14)',
      '--jse-input-background': '#1d2021',
      '--jse-key-color': '#83a598',
      '--jse-main-border': '1px solid #504945',
      '--jse-menu-color': '#ebdbb2',
      '--jse-modal-background': '#282828',
      '--jse-modal-code-background': '#1d2021',
      '--jse-navigation-bar-background': '#3c3836',
      '--jse-navigation-bar-background-highlight': '#504945',
      '--jse-panel-background': '#1d2021',
      '--jse-panel-background-border': '1px solid #504945',
      '--jse-panel-button-background-highlight': '#504945',
      '--jse-panel-color': '#ebdbb2',
      '--jse-selection-background-color': '#504945',
      '--jse-table-header-background': '#1d2021',
      '--jse-table-header-background-highlight': '#3c3836',
      '--jse-text-color': '#ebdbb2',
      '--jse-text-color-inverse': '#282828',
      '--jse-theme-color': '#fabd2f',
      '--jse-theme-color-highlight': '#fe8019',
      '--jse-tooltip-background': '#3c3836',
      '--jse-tooltip-border': '1px solid #504945',
      '--jse-value-color': '#ebdbb2',
      '--jse-value-color-boolean': '#d3869b',
      '--jse-value-color-null': '#d3869b',
      '--jse-value-color-number': '#d3869b',
      '--jse-value-color-string': '#b8bb26',
      '--jse-value-color-url': '#8ec07c',
    },
  },
  solarizedDark: {
    hint: '参考 VS Code 热门主题 Solarized Dark',
    label: 'Solarized Dark',
    preview: {
      background: '#002b36',
      color: '#839496',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(131, 148, 150, 0.07)',
      '--jse-background-color': '#002b36',
      '--jse-button-background': '#268bd2',
      '--jse-button-background-highlight': '#2aa198',
      '--jse-button-color': '#fdf6e3',
      '--jse-collapsed-items-background-color': '#073642',
      '--jse-context-menu-background': '#fdf6e3',
      '--jse-context-menu-background-highlight': '#eee8d5',
      '--jse-context-menu-color': '#002b36',
      '--jse-delimiter-color': '#586e75',
      '--jse-hover-background-color': 'rgba(38, 139, 210, 0.14)',
      '--jse-input-background': '#001f27',
      '--jse-key-color': '#268bd2',
      '--jse-main-border': '1px solid #073642',
      '--jse-menu-color': '#eee8d5',
      '--jse-modal-background': '#002b36',
      '--jse-modal-code-background': '#001f27',
      '--jse-navigation-bar-background': '#073642',
      '--jse-navigation-bar-background-highlight': '#124653',
      '--jse-panel-background': '#001f27',
      '--jse-panel-background-border': '1px solid #073642',
      '--jse-panel-button-background-highlight': '#073642',
      '--jse-panel-color': '#839496',
      '--jse-selection-background-color': '#073642',
      '--jse-table-header-background': '#001f27',
      '--jse-table-header-background-highlight': '#073642',
      '--jse-text-color': '#839496',
      '--jse-text-color-inverse': '#002b36',
      '--jse-theme-color': '#b58900',
      '--jse-theme-color-highlight': '#cb4b16',
      '--jse-tooltip-background': '#073642',
      '--jse-tooltip-border': '1px solid #586e75',
      '--jse-value-color': '#839496',
      '--jse-value-color-boolean': '#d33682',
      '--jse-value-color-null': '#d33682',
      '--jse-value-color-number': '#d33682',
      '--jse-value-color-string': '#859900',
      '--jse-value-color-url': '#2aa198',
    },
  },
  cobalt2: {
    hint: '参考 VS Code 热门主题 Cobalt2',
    label: 'Cobalt2',
    preview: {
      background: '#193549',
      color: '#ffffff',
    },
    requiresDarkBase: true,
    variables: {
      '--jse-active-line-background-color': 'rgba(255, 255, 255, 0.08)',
      '--jse-background-color': '#193549',
      '--jse-button-background': '#ffc600',
      '--jse-button-background-highlight': '#ff9d00',
      '--jse-button-color': '#193549',
      '--jse-collapsed-items-background-color': '#122738',
      '--jse-context-menu-background': '#ffffff',
      '--jse-context-menu-background-highlight': '#e9f0f7',
      '--jse-context-menu-color': '#193549',
      '--jse-delimiter-color': '#9effff',
      '--jse-hover-background-color': 'rgba(255, 198, 0, 0.14)',
      '--jse-input-background': '#102a3a',
      '--jse-key-color': '#9effff',
      '--jse-main-border': '1px solid #255b78',
      '--jse-menu-color': '#ffffff',
      '--jse-modal-background': '#193549',
      '--jse-modal-code-background': '#102a3a',
      '--jse-navigation-bar-background': '#122738',
      '--jse-navigation-bar-background-highlight': '#255b78',
      '--jse-panel-background': '#102a3a',
      '--jse-panel-background-border': '1px solid #255b78',
      '--jse-panel-button-background-highlight': '#255b78',
      '--jse-panel-color': '#ffffff',
      '--jse-selection-background-color': '#255b78',
      '--jse-table-header-background': '#102a3a',
      '--jse-table-header-background-highlight': '#122738',
      '--jse-text-color': '#ffffff',
      '--jse-text-color-inverse': '#193549',
      '--jse-theme-color': '#ffc600',
      '--jse-theme-color-highlight': '#ff9d00',
      '--jse-tooltip-background': '#122738',
      '--jse-tooltip-border': '1px solid #255b78',
      '--jse-value-color': '#ffffff',
      '--jse-value-color-boolean': '#ff628c',
      '--jse-value-color-null': '#ff628c',
      '--jse-value-color-number': '#ff628c',
      '--jse-value-color-string': '#a5ff90',
      '--jse-value-color-url': '#80fcff',
    },
  },
} as const

export type JsonEditorTheme = keyof typeof jsonEditorThemePresets

export interface JsonEditorThemeOption {
  hint: string
  label: string
  value: JsonEditorTheme
}

export const jsonEditorThemeOptions = Object.entries(jsonEditorThemePresets).map(
  ([value, preset]) => ({
    hint: preset.hint,
    label: preset.label,
    value: value as JsonEditorTheme,
  }),
) satisfies JsonEditorThemeOption[]

type EditorThemeStyle = Record<`--${string}`, string>

export function useJsonEditorTheme() {
  const selectedTheme = shallowRef<JsonEditorTheme>('dark')

  const activeTheme = computed(() => jsonEditorThemePresets[selectedTheme.value])

  const editorThemeClass = computed(() => ({
    'jse-theme-dark': activeTheme.value.requiresDarkBase,
  }))

  const editorThemeStyle = computed<EditorThemeStyle>(() => ({
    '--jse-font-family': 'var(--font-sans)',
    '--jse-font-family-mono': 'var(--font-mono)',
    ...activeTheme.value.variables,
  }))

  const previewThemeStyle = computed<Record<string, string>>(() => ({
    background: activeTheme.value.preview.background,
    color: activeTheme.value.preview.color,
  }))

  return {
    editorThemeClass,
    editorThemeStyle,
    previewThemeStyle,
    selectedTheme,
    themeOptions: jsonEditorThemeOptions,
  }
}
